2024-12-04 14:18:37,418 INFO    MainThread:3995260 [wandb_setup.py:_flush():79] Current SDK version is 0.18.7
2024-12-04 14:18:37,418 INFO    MainThread:3995260 [wandb_setup.py:_flush():79] Configure stats pid to 3995260
2024-12-04 14:18:37,418 INFO    MainThread:3995260 [wandb_setup.py:_flush():79] Loading settings from /zhome/32/9/137127/.config/wandb/settings
2024-12-04 14:18:37,418 INFO    MainThread:3995260 [wandb_setup.py:_flush():79] Loading settings from /zhome/32/9/137127/Master-Thesis/wandb/settings
2024-12-04 14:18:37,419 INFO    MainThread:3995260 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-12-04 14:18:37,419 INFO    MainThread:3995260 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-12-04 14:18:37,419 INFO    MainThread:3995260 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'scripts/lotka-volterra-upinn.py', 'program_abspath': '/zhome/32/9/137127/Master-Thesis/scripts/lotka-volterra-upinn.py', 'program': '/zhome/32/9/137127/Master-Thesis/scripts/lotka-volterra-upinn.py'}
2024-12-04 14:18:37,419 INFO    MainThread:3995260 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-12-04 14:18:37,419 INFO    MainThread:3995260 [wandb_init.py:_log_setup():533] Logging user logs to /zhome/32/9/137127/Master-Thesis/wandb/run-20241204_141837-0pwj3s90/logs/debug.log
2024-12-04 14:18:37,419 INFO    MainThread:3995260 [wandb_init.py:_log_setup():534] Logging internal logs to /zhome/32/9/137127/Master-Thesis/wandb/run-20241204_141837-0pwj3s90/logs/debug-internal.log
2024-12-04 14:18:37,419 INFO    MainThread:3995260 [wandb_init.py:init():619] calling init triggers
2024-12-04 14:18:37,419 INFO    MainThread:3995260 [wandb_init.py:init():626] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.001, 'Archtechture': 'KAN', 'Problem': 'Lotka-Volterra', 'Epochs': 10, 'Optimizer': 'AdamW'}
2024-12-04 14:18:37,419 INFO    MainThread:3995260 [wandb_init.py:init():669] starting backend
2024-12-04 14:18:37,419 INFO    MainThread:3995260 [wandb_init.py:init():673] sending inform_init request
2024-12-04 14:18:37,423 INFO    MainThread:3995260 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-12-04 14:18:37,423 INFO    MainThread:3995260 [wandb_init.py:init():686] backend started and connected
2024-12-04 14:18:37,432 INFO    MainThread:3995260 [wandb_init.py:init():781] updated telemetry
2024-12-04 14:18:37,447 INFO    MainThread:3995260 [wandb_init.py:init():814] communicating run to backend with 90.0 second timeout
2024-12-05 02:15:14,315 ERROR   MainThread:3995260 [wandb_init.py:init():841] encountered error: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
2024-12-05 02:15:14,316 ERROR   MainThread:3995260 [wandb_init.py:init():1266] error in wandb.init()
Traceback (most recent call last):
  File "/zhome/32/9/137127/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1256, in init
    return wi.init()
           ^^^^^^^^^
  File "/zhome/32/9/137127/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 847, in init
    raise error
wandb.errors.errors.CommError: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
2024-12-05 02:15:14,349 WARNING MsgRouterThr:3995260 [router.py:message_loop():75] message_loop has been closed
